const items = [
	{
		title: 'Twitter',
		href: 'https://twitter.com/theblueypodcast',
		icon: 'fa-brands fa-twitter',
		background: '#0d7ac4',
	},
	{
		title: 'Spotify',
		href: 'https://podcasters.spotify.com/pod/show/bluey-podcast/episodes/Mums-and-Dads-e26po6t',
		icon: 'fa-brands fa-spotify',
		background: '#16883e',
	},
	{
		title: 'Apple Podcasts',
		href: 'https://podcasts.apple.com/us/podcast/dinner-with-the-heelers/id1648081856',
		icon: 'fa-solid fa-podcast',
		background: 'var(--applePodcasts)',
	},
	{
		title: 'TikTok',
		href: 'https://www.tiktok.com/@theblueypodcast',
		icon: 'fa-brands fa-tiktok',
		background: '#eb004a',
	},
	{
		title: 'Instagram',
		href: 'https://www.instagram.com/theblueypodcast/',
		icon: 'fa-brands fa-instagram',
		background: '#c13584',
	},
	{
		title: 'Emails',
		href: 'mailto:blueypodcast@gmail.com',
		icon: 'fa-solid fa-mailbox-flag-up',
		background: '#52565e',
	},
	{
		title: 'PodBean',
		href: 'https://www.podbean.com/podcast-detail/dydni-285607/Dinner-with-the-Heelers-Podcast',
		icon: 'fa-solid fa-coffee-beans',
		background: 'hsl(79 65% 30% / 1)',
	},
	{
		title: 'Facebook',
		href: 'https://www.facebook.com/profile.php?id=100086726259418',
		icon: 'fa-brands fa-facebook',
		background: '#3b5998',
	},
	// {
	// 	title: 'TeePublic',
	// 	href: 'https://www.teepublic.com/user/jammed-transmissions',
	// 	icon: 'fak fa-teepublic',
	// 	background: '#374ECD',
	// },
	// {
	// 	title: 'Bluesky',
	// 	href: 'https://bsky.app/profile/cadbanesbounty.bsky.social',
	// 	icon: 'fa-solid fa-clouds',
	// 	background: '#0560ff',
	// },
	{
		title: 'Overcast',
		href: 'https://overcast.fm/itunes1648081856/dinner-with-the-heelers',
		icon: 'fak fa-overcast fa-lg',
		background: '#be5a01',
	},
	{
		title: 'Google Play',
		href: 'https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy9iZGNiZmI3MC9wb2RjYXN0L3Jzcw',
		icon: 'fa-brands fa-google-play',
		background: '#206ff2',
	},
	{
		title: 'RSS',
		href: 'https://anchor.fm/s/bdcbfb70/podcast/rss',
		icon: 'fa-solid fa-rss',
		background: '#ce4a0c',
	},
	{
		title: 'Goodpods',
		href: 'https://goodpods.com/podcasts/dinner-with-the-heelers-277737',
		icon: 'fak fa-goodpods',
		background: '#fcdb00',
		color: 'var(--bg)',
	},
	{
		title: 'Amazon Music',
		href: 'https://music.amazon.com/podcasts/6c9ee5c6-eb09-4424-a34a-334d967b2c67/dinner-with-the-heelers',
		icon: 'fa-brands fa-amazon',
		background: '#0077c1',
	},
	{
		title: 'iHeart',
		href: 'https://www.iheart.com/podcast/269-dinner-with-the-heelers-102741776/',
		icon: 'fak fa-iheart',
		background: '#C6002B',
	},
	{
		title: 'Pocket Casts',
		href: 'https://pca.st/vpuwalsl',
		icon: 'fak fa-pocket-casts',
		background: '#ea150d',
	},
	// {
	// 	title: 'Radio Public',
	// 	href: 'https://radiopublic.com/jammed-transmissions-a-star-wars-Wwogwa',
	// 	icon: 'fak fa-radio-public',
	// 	background: '#CE262F',
	// },
	{
		title: 'Castbox',
		href: 'https://castbox.fm/channel/Dinner-with-the-Heelers-id5156314',
		icon: 'fak fa-castbox',
		background: '#db3c0e',
	},
	{
		title: 'Family Portraits',
		href: 'https://www.instagram.com/blueyfamilyportraits/',
		icon: 'fa-solid fa-palette',
		background: 'var(--offText)',
	},
]

export default items
